name: iOS Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build-ios-unsigned:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build

      - name: Install Capacitor iOS
        run: npm i -D @capacitor/ios@latest

      - name: Add iOS platform
        run: npx cap add ios --skip-deps --yes

      - name: Sync Capacitor
        run: npx cap sync ios

      - name: Install CocoaPods (if needed)
        run: |
          sudo gem install cocoapods -N || true

      - name: Pod install
        working-directory: ios/App
        run: pod install --repo-update

      - name: Xcode build (unsigned .app)
        run: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Package .ipa
        run: |
          rm -rf Payload
          mkdir -p Payload
          cp -R build/Build/Products/Release-iphoneos/App.app Payload/
          ipa_name="ChurchMemoryMaster-unsigned-${{ github.sha }}.ipa"
          zip -r "$ipa_name" Payload
          echo "Created: $ipa_name"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: ChurchMemoryMaster-unsigned-*.ipa
          if-no-files-found: error
name: iOS Unsigned IPA (for sideload)

on:
  workflow_dispatch:

jobs:
  build-unsigned:
    runs-on: macos-14
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build web (Vite)
        run: npm run build

      - name: Install Capacitor CLI
        run: npm i -g @capacitor/cli

      - name: Install Capacitor iOS platform package
        run: npm install @capacitor/ios@^7

      - name: Add/Sync iOS platform
        run: |
          if [ ! -d ios ]; then
            npx cap add ios
          fi
          npx cap sync ios

      - name: Install Cocoapods
        run: |
          sudo gem install cocoapods -N
          cd ios/App && pod install --repo-update

      - name: Install xcpretty (for readable xcodebuild logs)
        run: |
          sudo gem install xcpretty -N || true

      - name: Build unsigned .app (CODE_SIGNING_ALLOWED=NO)
        run: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build/ios \
            CODE_SIGNING_ALLOWED=NO \
            build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Package to IPA
        run: |
          rm -rf Payload && mkdir -p Payload
          APP_PATH="build/ios/Build/Products/Release-iphoneos/App.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "App.app not found at $APP_PATH" && exit 1
          fi
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -r App-unsigned.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-unsigned
          path: App-unsigned.ipa


