name: iOS Unsigned IPA (for sideload)

on:
  workflow_dispatch:

jobs:
  build-unsigned:
    runs-on: macos-14
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build web (Vite)
        run: npm run build

      - name: Install Capacitor CLI
        run: npm i -g @capacitor/cli

      - name: Add/Sync iOS platform
        run: |
          if [ ! -d ios ]; then
            npx cap add ios --skip-dependencies
          fi
          npx cap sync ios

      - name: Install Cocoapods
        run: |
          sudo gem install cocoapods -N
          cd ios/App && pod install --repo-update

      - name: Install xcpretty (for readable xcodebuild logs)
        run: |
          sudo gem install xcpretty -N || true

      - name: Build unsigned .app (CODE_SIGNING_ALLOWED=NO)
        run: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build/ios \
            CODE_SIGNING_ALLOWED=NO \
            build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Package to IPA
        run: |
          rm -rf Payload && mkdir -p Payload
          APP_PATH="build/ios/Build/Products/Release-iphoneos/App.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "App.app not found at $APP_PATH" && exit 1
          fi
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -r App-unsigned.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-unsigned
          path: App-unsigned.ipa


